cc_binary(
    name = "identity",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["identity.cpp"]),
    deps = [
         "//fetch_teams/ledger/experimental/crypto:lib",
   ],
)

cc_binary(
    name = "sha256",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["sha256.cpp"]),
    deps = [
         "//fetch_teams/ledger/experimental/crypto:lib",
   ],
)
