cc_binary(
    name = "app",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["*.cpp"]),
    deps = [
        "//threading/src/cpp/lib:lib",
    ],
    data = [
    ]
    #linkshared = True,
    #linkstatic = True,
)
