cc_binary(
    name = "helloworld",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["*.cpp"]),
    deps = [
    ],
    data = [
    ]
    #linkshared = True,
    #linkstatic = True,
)

