cc_library(
    name = "lib",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = [
         "//threading/src/cpp/lib:lib",
         "//fetch_teams/ledger:lib",
    ],
)
