cc_library(
    name = "lib",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = [
         "//fetch_teams/ledger:lib",
         "//fetch_teams/ledger/experimental/meta:lib",
   ],
)
