cc_library(
    name = "lib",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = [
        "//cpp-utils/src/cpp/lib:lib",
        "//fetch_teams/ledger:lib",
    ],
)
