cc_binary(
    name = "uri-main",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["uri-main.cpp"]),
    deps = [
        "//cpp-utils/src/cpp/lib:lib"
    ],
    data = [
    ]
    #linkshared = True,
    #linkstatic = True,
)
