cc_binary(
    name = "oef-node-old",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["main.cpp"]),
    deps = [
        "//oef-core-functions/src/cpp/lib:liboef-old",
    ],
    data = [
    ]
    #linkshared = True,
    #linkstatic = True,
)
